Numpy Basic

In [2]:
#Consider the below code to answer further questions:

import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to
       print the data types of both the variables.'''

In [ ]:
#Ans.
Yes, there is difference in data types of variables list_ and array_list because list_ is a variable of python list which
containing integer in string form and his data type is 'list'.
Whereas array_list is a numpy array which data type is different from list. and its data type is 'numpy.ndarray'.

In [6]:
print('Data type of list_ is {}'.format(type(list_)))

Data type of list_ is <class 'list'>


In [7]:
print('Data type of array_list is {}'.format(type(array_list)))

Data type of array_list is <class 'numpy.ndarray'>


In [ ]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.'''

In [8]:
#Ans.

#Variable list
list_ 

['1', '2', '3', '4', '5']

In [9]:
#Array list
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [10]:
#each element's data type of variable list_
for i in list_ :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
#each elememt's data type of array_list
for i in  array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
'''Q3. Considering the following changes in the variable, array_list:

       array_list = np.array(object = list_, dtype = int)
       
       Will there be any difference in the data type of the elements present in both the variables, list_ and
       arra_list? If so then print the data types of each and every element present in both the variables, list_
       and arra_list.'''

In [ ]:
#Ans.
Yes, there is difference in both variables array_list and list_ , after applying condition in array_list variable. 
array_list elements data type is changed from string to int64 and data type of element of list_ is same (string) . So 
there is difference in data types of elements.

In [12]:
#modified array_list 
array_list = np.array(object = list_, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
# variable list
list_

['1', '2', '3', '4', '5']

In [17]:
#data type of elements of array_list variable
for elements in array_list :
    print(type(elements))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
#data type of elements of list_ variable
for elements in list_ :
    print(type(elements))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [ ]:
'''Consider the below code to answer further questions:
    import numpy as np
    num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
    num_array = np.array(object = num_list)'''

In [19]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [23]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [21]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#element's data type of num_list
for lis in num_list :
    for element in lis :
        print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [28]:
#element's data type of num_array
for array in num_array:
    for element in i :
        print(type(element))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
There is no any difference in data type of elements of both variables num_list and num_array because both variables 
contain same type of element (int data).

In [ ]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
    (i) shape
    (ii) size'''

In [29]:
#Ans.
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#(i) shape
Shape function in numpy describe about the shape of array by showing the rows and columns present in array.

In [33]:
np.shape(num_array)

(2, 3)

In [ ]:
#(ii) size
Size function in numpy library describe about the size of array by showing the number of elements present in array.

In [34]:
np.size(num_array)

6

In [ ]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.'''

In [51]:
#Ans.
import numpy.matlib as nm

In [54]:
m = nm.zeros((3,3))

In [55]:
m

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [56]:
nm.size(m)

9

In [57]:
nm.shape(m)

(3, 3)

In [ ]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?'''

In [58]:
#Ans.
import numpy.matlib as nm

In [60]:
#identity matrix
nm.eye(5,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
                         ◦•●◉✿ ❤️️' 𝐉 𝐀 𝐈   𝐒 𝐇 𝐑 𝐄 𝐄   𝐇 𝐀 𝐑 𝐈   𝐕 𝐈 𝐒 𝐇 𝐍 𝐔 '❤️ ✿◉●•◦